package com.parcelproof;
enum UserRole{ADMIN,DISPATCHER,DRIVER,CUSTOMER} enum UserStatus{ACTIVE,DISABLED} enum VehicleType{BIKE,THREE_WHEELER,VAN,LORRY} enum AvailabilityStatus{AVAILABLE,ON_DELIVERY,OFFLINE} enum CustomerType{INDIVIDUAL,BUSINESS}
enum ParcelType{DOCUMENT,SMALL_PACKAGE,FRAGILE,ELECTRONICS,FOOD,CLOTHING,OTHER} enum PaymentStatus{PENDING,PAID,CASH_ON_DELIVERY} enum ParcelPriority{LOW,NORMAL,HIGH,EXPRESS}
enum ParcelStatus{BOOKED,ASSIGNED,PICKED_UP,IN_TRANSIT,OUT_FOR_DELIVERY,DELIVERED,FAILED_ATTEMPT,RETURNED,CANCELLED} enum AttemptStatus{SUCCESSFUL,FAILED} enum FailureReason{CUSTOMER_NOT_AVAILABLE,WRONG_ADDRESS,PHONE_NOT_REACHABLE,PAYMENT_NOT_READY,WEATHER_DELAY,VEHICLE_ISSUE,OTHER}
